[package]
name = "wavebreaker_up"
version = "1.0.0"
edition = "2021"

[dependencies]
eframe = "0.32.1"
catppuccin-egui = { version = "5.1", default-features = false, features = [
    "egui27",
] }
octocrab = "0.44.0"
tokio = { version = "1.47.1", features = ["full"] }
anyhow = "1.0.82"
env_logger = "0.11.3"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
tracing = "0.1.40"
lazy_async_promise = "0.6.0"
reqwest = "0.12.4"
zip-extract = "0.4.1"
open = "5.1.2"
sysinfo = "0.37.0"
