#![allow(clippy::missing_transmute_annotations)] // silence clippy warnings generated by the crochet::hook macro

use std::{
    ffi::{c_char, c_int, c_void, CStr, CString, OsString},
    mem,
    os::windows::ffi::OsStringExt,
};

use lofty::{prelude::*, tag::ItemValue};
use tracing::{debug, error, info, trace};
use url_encoded_data::UrlEncodedData;
use windows::{
    core::{s, PCSTR, PSTR},
    Win32::{
        Networking::WinInet::{
            InternetQueryOptionA, INTERNET_FLAG_RELOAD, INTERNET_FLAG_SECURE, INTERNET_OPTION_URL,
        },
        System::LibraryLoader::GetModuleHandleA,
        UI::Controls::Dialogs::OPENFILENAMEA,
    },
};

use crate::{
    config::CONFIG,
    q3d_bindings::{
        A3d_Channel, Aco_FloatChannel, Aco_StringChannel, Aco_StringChannel_GetString,
        Aco_StringChannel_SetString,
    },
    state,
};

// from https://stackoverflow.com/a/48587463
// credit to Boiethios
unsafe fn u16_ptr_to_string(ptr: *const u16) -> OsString {
    let len = (0..).take_while(|&i| *ptr.offset(i) != 0).count();
    let slice = std::slice::from_raw_parts(ptr, len);

    OsString::from_wide(slice)
}

#[crochet::hook("BASS_PreCalcSong.dll", "?CallChannel@Aco_BASS_PreCalcSong@@UAEXXZ")]
unsafe extern "thiscall" fn precalcsong_call_hook(this: *mut A3d_Channel) {
    call_original!(this);

    let channel = this.as_mut().unwrap();
    let song_source = channel
        .GetChild(1)
        .cast::<Aco_FloatChannel>()
        .as_mut()
        .unwrap()
        .channelFloat_;

    debug!("PreCalc with source {}", song_source);

    // Seperate scope to unlock mutex sooner
    {
        let mut global_data = state::GLOBAL_DATA.lock().unwrap();
        global_data.current_mbid = None;
        global_data.current_release_mbid = None;
    }

    // 0 = File
    // 1 = CD
    // 2 = Buffer
    if song_source != 0.0 {
        return;
    }

    let module_base = GetModuleHandleA(s!("bass.dll")).unwrap().0 as *mut c_void;
    debug!("BASS module base: {:?}", module_base);
    let module_base = module_base.add(0x000351B4);
    debug!("Offset 0: {:?}", module_base);
    let offset_1 = *(module_base as *const u32) as *mut c_void;
    debug!("Offset 1: {:?}", offset_1);
    let offset_2 = *(offset_1 as *const u32) as *mut c_void;
    debug!("Offset 2: {:?}", offset_2);
    let offset_3 = offset_2.add(0x90);
    let offset_3 = *(offset_3 as *const u32) as *mut c_void;
    debug!("Offset 3: {:?}", offset_3);
    let offset_4 = offset_3.add(0x44);
    let offset_4 = *(offset_4 as *const u32) as *mut c_void;
    debug!("Final: {:?}", offset_4);
    let path_from_ptr = u16_ptr_to_string(offset_4.cast());
    match path_from_ptr.to_str() {
        Some(path) => {
            debug!("Path from ptr: {:?}", path);
            path
        }
        None => {
            error!("Failed to get song path from ptr");
            return;
        }
    };

    match lofty::read_from_path(path_from_ptr) {
        Ok(res) => {
            let tag = res.primary_tag();
            match tag {
                Some(tag) => {
                    match tag.get(&ItemKey::MusicBrainzRecordingId) {
                        Some(item) => match item.value() {
                            ItemValue::Text(mbid) => {
                                let mut global_data = state::GLOBAL_DATA.lock().unwrap();
                                global_data.current_mbid = Some(mbid.to_string());
                                info!("Recording MBID tag found: {:?}", mbid);
                            }
                            _ => {
                                error!("Recording MBID tag is an invalid data type...?");
                            }
                        },
                        _ => {
                            debug!("File has no recording MBID");
                        }
                    };

                    match tag.get(&ItemKey::MusicBrainzReleaseId) {
                        Some(item) => match item.value() {
                            ItemValue::Text(mbid) => {
                                let mut global_data = state::GLOBAL_DATA.lock().unwrap();
                                global_data.current_release_mbid = Some(mbid.to_string());
                                info!("Release MBID tag found: {:?}", mbid);
                            }
                            _ => {
                                error!("Release MBID tag is an invalid data type...?");
                            }
                        },
                        _ => {
                            debug!("File has no release MBID");
                        }
                    };
                }
                None => {
                    debug!("File has no tags");
                }
            }
        }
        Err(e) => {
            error!("lofty::read_from_path failed {:?}", e);
        }
    };
}

#[crochet::hook(compile_check, "Wininet.dll", "HttpSendRequestA")]
unsafe fn send_hook(
    hrequest: *const c_void,
    headers: PCSTR,
    headers_len: u32,
    optional: *mut c_void,
    optional_len: u32,
) -> c_int {
    if optional.is_null() || optional_len == 0 {
        trace!(
            "send_hook called without data {:?}",
            CString::from_vec_unchecked(headers.as_bytes().to_vec()),
        );
        return call_original!(hrequest, headers, headers_len, optional, optional_len);
    }

    // Get the URL so we know where the request is going
    let mut lpbuffer = [0u8; 1024];
    let mut lpdwbufferlength = mem::size_of_val(&lpbuffer) as u32;
    let _ = InternetQueryOptionA(
        Some(hrequest),
        INTERNET_OPTION_URL,
        Some(lpbuffer.as_mut_ptr() as *mut c_void),
        &mut lpdwbufferlength as *mut u32,
    );

    // Cut the buffer and convert to string
    let url = CString::from_vec_unchecked(lpbuffer[..lpdwbufferlength as usize].to_vec());
    let url = url.to_str().unwrap();

    //with length and pointer, read the optional data
    let data = std::slice::from_raw_parts(optional as *const u8, optional_len as usize);
    let data = std::str::from_utf8(data).unwrap();
    trace!(
        "send_hook called: {:?} {:?}",
        CString::from_vec_unchecked(headers.as_bytes().to_vec()),
        data
    );
    let form_data = UrlEncodedData::parse_str(data);
    let mut new_form_data = form_data.clone();

    let mut global_data = state::GLOBAL_DATA.lock().unwrap();

    // store ticket for our own uses
    if form_data.exists("ticket") && global_data.ticket.is_none() {
        let ticket = form_data.get_first("ticket").unwrap();
        global_data.ticket = Some(ticket.to_string());
        debug!("Ticket found in data: {:?}", ticket);
    }

    // Add client version when:
    // - fetching song ID
    // - attempting to login
    // - fetching custom news
    // - submitting a score
    if url.ends_with("/as_steamlogin/game_fetchsongid_unicode.php")
        || url.ends_with("/as_steamlogin/game_AttemptLoginSteamVerified.php")
        || url.ends_with("//as_steamlogin/game_CustomNews.php")
        || url.ends_with("/as_steamlogin/game_SendRideSteamVerified.php")
    {
        new_form_data.set_one("wvbrclientversion", env!("CARGO_PKG_VERSION"));
    }

    // Add Steam auth ticket when fetching song ID
    if url.ends_with("/as_steamlogin/game_fetchsongid_unicode.php") {
        if let Some(ticket) = &global_data.ticket {
            new_form_data.set_one("ticket", ticket);
        }
    }

    // Add recording and release MBIDs (if present), when fetching song ID and submitting a score
    if url.ends_with("/as_steamlogin/game_fetchsongid_unicode.php")
        || url.ends_with("/as_steamlogin/game_SendRideSteamVerified.php")
    {
        if let Some(mbid) = &global_data.current_mbid {
            new_form_data.set_one("mbid", mbid);
        }
        if let Some(release_mbid) = &global_data.current_release_mbid {
            new_form_data.set_one("releasembid", release_mbid);
        }
    }

    // if nothing changed, we don't need to allocate a new string
    if new_form_data.to_string_of_original_order() == form_data.to_string_of_original_order() {
        call_original!(hrequest, headers, headers_len, optional, optional_len)
    } else {
        let new_data_string = new_form_data.to_string_of_original_order();
        let new_data = malloc_c_string(&new_data_string) as *mut c_void; // allocate new string

        call_original!(
            hrequest,
            headers,
            headers_len,
            new_data,
            new_data_string.len() as u32
        )
    }
}

#[crochet::hook(compile_check, "Wininet.dll", "InternetConnectA")]
unsafe fn connect_hook(
    hinternet: c_int,
    server_name: PCSTR,
    mut port: u16,
    username: PCSTR,
    password: PCSTR,
    service: u32,
    flags: u32,
    context: usize,
) -> c_int {
    trace!(
        "connect_hook called: {:?} {:?}",
        CString::from_vec_unchecked(server_name.as_bytes().to_vec()),
        port
    );
    let config = CONFIG.get().unwrap();
    if config.main.force_insecure && port == 443 {
        port = 80;
    } else if !config.main.force_insecure && port == 80 {
        port = 443;
    }

    call_original!(
        hinternet,
        server_name,
        port,
        username,
        password,
        service,
        flags,
        context
    )
}

#[crochet::hook(compile_check, "Wininet.dll", "HttpOpenRequestA")]
unsafe fn openrequest_hook(
    hconnect: c_int,
    verb: PCSTR,
    object_name: PCSTR,
    version: PCSTR,
    referrer: PCSTR,
    accept_types: *const PCSTR,
    mut flags: u32,
    context: usize,
) -> c_int {
    trace!(
        "openrequest_hook called: {:?} {:?} {:?}",
        verb.to_string().unwrap(),
        object_name.to_string().unwrap(),
        flags
    );

    let config = CONFIG.get().unwrap();
    if config.main.force_insecure {
        flags &= !INTERNET_FLAG_SECURE;
    } else {
        if flags == 0 {
            flags = INTERNET_FLAG_SECURE;
        }
        if flags == INTERNET_FLAG_RELOAD {
            flags = INTERNET_FLAG_RELOAD | INTERNET_FLAG_SECURE;
        }
    }
    debug!("new OpenRequest flags: {:?}", flags);

    call_original!(
        hconnect,
        verb,
        object_name,
        version,
        referrer,
        accept_types,
        flags,
        context
    )
}

#[crochet::hook(
    "HTTP_Fetch_Unicode.dll",
    "?GetTargetServer@HTTP_Fetch_Unicode@@UAEPADXZ"
)]
unsafe extern "thiscall" fn gettargetserver_unicode_hook(this_ptr: c_int) -> *const c_char {
    trace!("gettargetserver_unicode_hook called: {:?}", this_ptr);

    let orig_result = call_original!(this_ptr);
    let c_str = CStr::from_ptr(orig_result);
    trace!(
        "gettargetserver_unicode_hook original result: {:?}",
        c_str.to_str()
    );

    let new_str = rewrite_server(c_str.to_str().unwrap());
    debug!("Server rewritten to: {:?}", &new_str);

    malloc_c_string(&new_str) as *const c_char
}

#[crochet::hook(
    "17C5B19F-4273-423C-A158-CA6F73046D43.dll",
    "?GetTargetServer@Aco_HTTP_Fetch@@UAEPADXZ"
)]
unsafe extern "thiscall" fn gettargetserver_hook(this_ptr: c_int) -> *const c_char {
    trace!("gettargetserver_hook called: {:?}", this_ptr);

    let orig_result = call_original!(this_ptr);
    let c_str = CStr::from_ptr(orig_result);
    trace!("gettargetserver_hook original result: {:?}", c_str.to_str());

    let new_str = rewrite_server(c_str.to_str().unwrap());
    debug!("Server rewritten to: {:?}", &new_str);

    malloc_c_string(&new_str) as *const c_char
}

#[crochet::hook("FolderExploder.dll", "?CallChannel@FolderExploder@@UAEXXZ")]
unsafe extern "thiscall" fn call_folderexploder_hook(this: *mut A3d_Channel) {
    trace!("call_folderexploder_hook called");
    let channel = this.as_mut().unwrap();

    let filters_channel = channel.GetChild(7).cast::<Aco_StringChannel>();
    let filters = CStr::from_ptr(Aco_StringChannel_GetString(filters_channel.cast()))
        .to_str()
        .unwrap();
    if !filters.contains("opus") {
        debug!("Adding opus to FolderExploder filters");
        Aco_StringChannel_SetString(
            filters_channel.cast(),
            malloc_c_string(&(filters.to_owned() + ",opus")).cast(),
        );
    }

    call_original!(this);
}

#[crochet::hook("comdlg32.dll", "GetOpenFileNameA")]
unsafe fn getopenfilename_hook(param: *mut OPENFILENAMEA) -> i32 {
    trace!("getopenfilename_hook called");

    let param = param.as_mut().unwrap();
    let filter = param.lpstrFilter;
    let filter = filter.to_string().unwrap();
    let mut filter: Vec<&str> = filter.split(", ").collect();
    //arbitrary way to check if the filter is for audio files
    if filter.contains(&"mp3") && filter.contains(&"flac") {
        filter.push("opus");
    }

    let path = rfd::FileDialog::new()
        .set_title("File dialog (hooked)")
        .add_filter("Supported files", &filter)
        .pick_file();

    match path {
        Some(path) => {
            debug!("Selected file: {:?}", path);
            let path_ptr = malloc_c_string(path.to_str().unwrap());
            param.lpstrFile = PSTR(path_ptr.cast());
            1
        }
        None => {
            debug!("No file selected");
            0
        }
    }
}

unsafe fn malloc_c_string(s: &str) -> *mut () {
    // this is an absolute meme
    let c_str = CString::new(s).unwrap();
    let memory = malloc(c_str.as_bytes_with_nul().len());
    std::ptr::copy_nonoverlapping(
        c_str.as_bytes_with_nul().as_ptr(),
        memory as *mut u8,
        c_str.as_bytes_with_nul().len(),
    );
    memory
}

extern "C" {
    fn malloc(n: usize) -> *mut ();
}

fn rewrite_server(server: &str) -> String {
    let config = CONFIG.get().unwrap();
    if server.contains("audiosurfthegame") || server.contains("audio-surf") {
        config.main.server.clone()
    } else {
        server.to_string()
    }
}

pub fn init_hooks() -> anyhow::Result<()> {
    crochet::enable!(connect_hook)?;
    crochet::enable!(openrequest_hook)?;
    crochet::enable!(gettargetserver_unicode_hook)?;
    crochet::enable!(gettargetserver_hook)?;
    crochet::enable!(send_hook)?;
    crochet::enable!(precalcsong_call_hook)?;
    crochet::enable!(getopenfilename_hook)?;
    crochet::enable!(call_folderexploder_hook)?;

    Ok(())
}

pub fn deinit_hooks() -> anyhow::Result<()> {
    crochet::disable!(connect_hook)?;
    crochet::disable!(openrequest_hook)?;
    crochet::disable!(gettargetserver_unicode_hook)?;
    crochet::disable!(gettargetserver_hook)?;
    crochet::disable!(send_hook)?;
    crochet::disable!(precalcsong_call_hook)?;
    crochet::disable!(getopenfilename_hook)?;
    crochet::disable!(call_folderexploder_hook)?;

    Ok(())
}
